### PR TITLE
ci: add .build.yml

### PR DESCRIPTION
**Pull request by emersion**
https://builds.sr.ht/~emersion/job/22153

### CODE REVIEW

**Comment by ddevault** [comment]
Can we do this on Alpine instead?

**Comment by emersion** [comment]
The only concern I have about Alpine for Sway CI is that their wayland and wayland-protocols versions are often outdated, and even if I send patches they take a few months to get merged.

**Comment by ddevault** [comment]
I'm not too worried about that for swayidle & swaylock, they already have what they need to get the job done and I doubt the other protocols they depend on are going to be added to wayland-protocols any time soon.

**Comment by emersion** [comment]
That's fair. Updated.

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
